# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  twitter:
    consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
    consumer_secreet: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
    secret_key: <%= ENV['TWITTER_SECRET_KEY'] %>
    secret_secreet: <%= ENV['TWITTER_SECRET_SECRET'] %>

development:
  <<: *default
  secret_key_base: 09a190ebb68e89da08f278323acca34a4c4cf6cac99e3e71e1fef03b18201de730b0069d90f0953317771459036d8553b03745135fa58b5874e35430e4f0b9ff

test:
  <<: *default
  secret_key_base: 8ae5c61d92af61eb3cc0433b6233d014053e81c48790c61043a47e9dc3e0af2584e61eb45c4813474a7c662b178f431cfe0846103c9c9ece96da619783cb4369

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
